### ISSUE TITLE
'pull' не срабатывает, если не указан хост

### ISSUE THREAD

**Issue by Skorpyon** [renskiy/fabricio#117]
Собираю образ, пытаюсь его запулить в локал регистри (у меня потом на базе этого образа собирается основной)
`.pull` не срабатывает, так как не указан хост в таске, но мне же хост и не нужен, `registry` то указан, я хочу просто сохранить образ, а следующий таск уже соберет основной на его базе и запулит его на бой.

`'pull' execution was skipped due to no host provided (command: edcontainer.pull)`

Можно ли подумать над изменением этой логики?

**Comment by renskiy** [comment]
`pull` всегда выполняется на удаленном хосте (поэтому для этой команды всегда нужен host). В вашем случае можно использовать команду `prepare` для pull и `push` для загрузки образа в кастомный registry (логика похожа на случай со сборкой образа). Попробуйте например вот такую конфигурацию :
```python
from fabricio import tasks, docker

nginx = tasks.DockerTasks(
    service=docker.Container(
        name='nginx',
        image='nginx:stable-alpine',
    ),
    registry='your.private.registry',  # это ваш local registry
)
```

**Comment by Skorpyon** [comment]
Я похоже перепутал пулл и пуш )))
Я имел ввиду после сборки пушится ли собранный образ в custom registry.
Насколько я понял `.prepare` это и делает? Если без `pull`.
Т.е. у меня кейс такой:
- я собираю образ с python3.6, ставлю все зависимости и сохраняю в custom registry
- после этого я, на базе этого образа, собираю второй в который просто ставлю `application` и деплою его на сервер.

В принципе все так и получилось, я только не понял, fabricio незаметно для меня первые образ запушил локально или это registry его просто подхватило, т.к. он же на одной машине сбилдился.

Спасибо за тулзу, присматривался еще с первых статей на хабре, вот второй день юзаю.
!!!

**Comment by Skorpyon** [comment]
Есть предложение, в постгресовом контейнере есть `update` методы, которые заменяют настройки на локальные.
Очень удобный функционал.
Можно сделать его в отдельном миксине, чтобы потом можно было классы контейнеров с его помощью делать.
Мне бы, например, сейчас в nginx'e переписать nginx.conf вместо того, чтобы ему конфиги биндить из репозитория, склонированного на сервер.

**Comment by renskiy** [comment]
Пожалуйста за тулзу :)

А насчет конфигов, для Nginx конфиги можно в сам образ упаковывать. Случай с PostgreSQL отличается тем, что конфиги у него хранятся вместе с данными - именно из за этого и понадобился такой механизм обновления. Насчёт вынесения в отдельный mixin я подумаю
