### ISSUE TITLE
AttributeError: 'module' object has no attribute 'BuildDockerTasks'

### ISSUE THREAD

**Issue by Dmdv** [renskiy/fabricio#174]
Ubuntu 17.10
python2, python3
Fabric 1.13.1
Paramiko 2.0.0
fabricio Version: 0.5.6

Running fab -l causes 

AttributeError: 'module' object has no attribute 'BuildDockerTasks'

**Comment by renskiy** [comment]
What version of `fabricio` do you use? (run `pip freeze`). `BuildDockerTasks` was removed in version 0.4, you should use `ImageBuildDockerTasks` instead. Try to downgrade to version 0.3.26: `pip install -U fabricio==0.3.26`, fix all warnings and upgrade to latest version again.

**Comment by Dmdv** [comment]
Fabric==1.14.0
fabricio==0.5.6
