### ISSUE TITLE
denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by Dmdv** [renskiy/fabricio#175]
During installation encountered the following error:

fabricio.operations.Error: local() encountered an error (return code 1) while executing 'docker push...

**Environment:**
Mac OS 10.x
Fabric==1.14.0
fabricio==0.5.6

denied: requested access to the resource is denied

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)

...

**Comment by Dmdv** [comment]
It definitely refers to docker repository located at docker.io/library/...
Which is not it's supposed to do, it must push to local registry instead of global

**Comment by renskiy** [comment]
Hi, it seems that you already done with this issue :) Anyway, take a look to [this example](https://github.com/renskiy/fabricio/tree/master/examples/hello_world#intermediate-proxy-registry) if you want to use local registry as proxy or [this](https://github.com/renskiy/fabricio/tree/master/examples/build_image) for just-in-time image building and deploying to remote host(s).
