### ISSUE TITLE
Docker stack. Links in docker-compose are ignored.

### ISSUE THREAD

**Issue by rivmar** [renskiy/fabricio#176]
Hi.
I tried to use fabricio to deploy my django project to prod.
I used docker and docker-compose before on local so I created docker.Stack service with link to my docker-compose file.
But the problem is that fabricio copies docker-compose.yml to /tmp and looks for all files, linked in docker-compose.yml, in this directory. For example, my docker-compose.yml has line:
```
env_file:
          - docker/dev.env
```
And at building container, docker looks for env file in /tmp/docker/dev.env and I get error.
What is worse, dockerfiles are not found too.
I tried:
1) Create docker.Stack with temp_dir parameter
2) Subclass Stack and point temp_dir to my project directory (and re-define upload_configuration_file)
3) Create symlink in tmp to my project directory.
Without any success.
Did I miss something important?

**Comment by renskiy** [comment]
Hi, have you tried to change `temp_dir` param? Like this:
```python
docker.Stack(
    ...
    temp_dir='path_to_folder_with_env_file',
)
```

**Comment by rivmar** [comment]
I got error:

> maria@home:~/job/$ fab django
[localhost] local: vagrant ssh-config
Added host: vagrant@172.28.128.3
Added host: vagrant@172.28.128.4
Added host: vagrant@172.28.128.5
[vagrant@172.28.128.3] Executing task 'upgrade'
[vagrant@172.28.128.3] run: docker info 2>&1 | grep "Is Manager:"
[vagrant@172.28.128.3] put: <file obj> -> /home/maria/job/docker-compose-prod.yml

>Fatal error: put() encountered an exception while uploading '<_io.BytesIO object at 0x7f9a280a5db0>'

>Underlying exception:
    No such file

>Aborting.
[vagrant@172.28.128.3] run: rm -f docker-compose-prod.yml
Disconnecting from vagrant@127.0.0.1:2222... done.
Disconnecting from vagrant@127.0.0.1:2200... done.
Disconnecting from vagrant@127.0.0.1:2201... done.
Disconnecting from vagrant@172.28.128.3... done.

But address is correct:

>maria@home:~/job$ cat /home/maria/job/docker-compose-prod.yml
version: '3'
services:

>    db:
     # container_name: postgres
      image: postgres:latest
...

I tried to change permissions for docker-compose-prod.yml, it did not help.

**Comment by renskiy** [comment]
can you also provide `temp_dir` value? It should point to the folder on remote server side.

**Comment by rivmar** [comment]
It's full error traceback, just markup break quote on empty lines.

> It should point to the folder on remote server side.

Why on remote?
I get temp_dir with os.getcwd() so it's my project folder. Is it wrong?

**Comment by renskiy** [comment]
> Why on remote?

because this folder is used as temporary to upload `docker-compose.yaml` on remote server. By default Fabricio uses `/tmp` for this purpose.

Most probably your case is slightly different then Fabricio expects to be used in. For instance, Fabricio doesn't expect that `docker-compose.yaml` depends on other files (e.g. `.env` or `Dockerfile`). If you wish so the only way to do it now is placing necessary files in special folder on remote server and providing path to this folder in `temp_dir`.

BTW, what version of Docker Compose file do you use? Fabricio works well with version 3 and most probably with version 2. I'm not sure if version 1 will work with Fabricio.

**Comment by rivmar** [comment]
>For instance, Fabricio doesn't expect that docker-compose.yaml depends on other files (e.g. .env or Dockerfile). 
So sad...
Ok, we will look for another way to deploy.
Thank you very much.

**Comment by renskiy** [comment]
You are welcome. There is another way to do with your deploy issue. Because of Fabricio is based on Fabric you can write Fabric task to upload necessary files and run it with Fabricio tasks. This should work for you.
