### ISSUE TITLE
start multiple dockers

### ISSUE THREAD

**Issue by rizplate** [renskiy/fabricio#182]
can I start 4 running versions of same docker image?

I see a replicas option, can It be used to spin 3 dockers

**Comment by renskiy** [comment]
Yes, you can. But `replicas` is used to start [Docker service](https://docs.docker.com/engine/reference/commandline/service_create/), not a single container.

Could you explain your case in more details? Do you want to start containers from the image on the same node? Are these containers have same options and start the same process?

**Comment by Saad-2013** [comment]
can i use Fabricio to write a script that take an argument from the shell and build docker-compose according to the provided args

**Comment by renskiy** [comment]
@Saad-2013 no, the only method that takes args from shell is [ImageBuildDockerTasks.prepare](
https://github.com/renskiy/fabricio/tree/master/examples/build_image#custom-build-params)

All other methods use args from the service (or task) definition. See examples.

Also you can create feature request.
