### ISSUE TITLE
Upload compose-file for docker stack

### ISSUE THREAD

**Issue by cizarco** [renskiy/fabricio#183]
I cannot upload a compose-file from a folder other than the fabfile.py folder since the "upload_configuration_file" script will try to upload it to the path of the mentioned local folder.
Example:
stack = tasks.DockerTasks(
    service=docker.Stack(
        name='stack',
        options={
            'compose-file':'/folder0/../foldern/docker-compose.yml',
        },
    ),
    hosts=fab.env.hosts,
    destroy_command=True,
)

fab will try to upload the docker-compose file to "/folder0/../foldern/docker-compose.yml" and not to temp_dir folder which will cause error if the path does not exist in the distant machine

**Comment by renskiy** [comment]
Hi. It is an error indeed. I'll fix it soon in the next version. Thanks.
